app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::Auth();

Route::get('/', function () {
    return view('index');
});

Route::get('/dashboard', [
    'as' => 'dashboard',
    'uses' => 'HomeController@home'
]);

//Social Login
Route::get('social/{provider?}', 'SocialController@getSocialAuth');
Route::get('social/callback/{provider?}', 'SocialController@getSocialAuthCallback');

Route::group(['prefix' => 'dashboard'], function(){

    Route::get('/dashboard', [
        'as' => 'dashboard',
        'uses' => 'HomeController@home'
    ]);

    Route::get('/home', [
        'as' => 'home',
        'uses' => 'HomeController@home'
    ]);

    Route::resource('contact', 'ContactController');
});

app/Contact.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    protected $table = 'contacts';

    protected $fillable = [
      'user_id', 'name', 'surname', 'email', 'phone'
    ];

    public function details()
    {
        // hasmany: A Contact has many details
        return $this->hasMany(Detail::class);
    }

    public function user()
    {
        // belongsto: Contact belongs to User
        return $this->belongsTo(User::class);
    }
}

app/Detail.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Detail extends Model
{
    protected $table = 'details';

    protected $fillable = [
      'contact_id', 'description'
    ];

    public function contact()
    {
        // belongsto: Detail belongs to Contact
        return $this->belongsTo(Contact::class);
    }
}

app/Social.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Social extends Model
{
    protected $table = 'user_social_accounts';
    public $timestamps = false;
}

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'surname', 'username', 'phone', 'email', 'password', 'social',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function contacts()
    {
        // hasmany: A User has many contacts
        return $this->hasMany(Contact::class);
    }
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Contact;
use Auth;

class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user_id = Auth::user()->id;
        $contacts = Contact::all()->where('user_id', '=', $user_id);
        return view('dashboard.home', compact('contacts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.contacts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if($request->ajax()) {
            $request['user_id'] = Auth::user()->id;
            $record = Contact::create($request->all());
            $data = array('error'=>0, 'id'=>$record['id']);
            return response()->json($data);
        } else {
            return response()->json(
                ["error" => 1]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return Contact::find($id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $contacts = Contact::findOrFail($id);
        return view('dashboard.contacts.edit');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if($request->ajax()) {
            $input = $request->all();
            $record = Contact::findOrFail($id);
            $data = $record->update($input);
            return response()->json($data);
        } else {
            return response()->json(
                ["error" => 1]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $contact = Contact::find($id);
        $contact->delete();
        return response()->json($id);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesResources;

class Controller extends BaseController
{
    use AuthorizesRequests, AuthorizesResources, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use Illuminate\Http\Request;
use App\Contact;
use Auth;
use DB;
use Response;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function home()
    {
        // return view('dashboard.home');
        //$contacts = Contact::all();
        // $contacts = Contact::paginate(20);
        $user_id = Auth::user()->id;
        $contacts = DB::table('contacts')->where('user_id', $user_id)->orderBy('name', 'asc')->get();
        return view('dashboard.home', ['contacts' => $contacts]);
        // return Response::json($contacts, 200);
    }
}

app/Http/Controllers/SocialController.php
<?php

namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\User;
use App\Social;
use Auth;
use Socialite;

class SocialController extends Controller {

    public function __construct(){
     $this->middleware('guest');
    }

       public function getSocialAuth($provider=null)
       {
           if(!config("services.$provider")) abort('404');

           return Socialite::driver($provider)->redirect();
       }


       public function getSocialAuthCallback($provider=null)
       {
          if($user = Socialite::driver($provider)->user()) {
             if($the_user = User::select()->where('email', '=', $user->email)->first()) {
                 Auth::login($the_user);
             } else {
                 $new_user = new User;
                 $new_user->name = $user->name;
                 $new_user->email = $user->email;
                 $new_user->social = 1;
                 $new_user->save();
                 Auth::login($new_user);
                 $social = new Social;
                 $social->user_id = $new_user->id;
                 $social->provider = $provider;
                 $social->uid_provider = $user->id;
                 $social->save();
             }
             return redirect('/dashboard/home');
          }else{
             return redirect('/dashboard/home');
          }
       }
}

resources/views/dashboard/home.blade.php
@extends('templates.public')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading text-center"><h3><strong>{{ trans('messages.contactList') }}</strong></h3></div>

                <div class="panel-body">
                    <div class="form-group">
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#createContactModal">{{ trans('messages.addContact') }}</button>
                    </div>
                    @if(count($contacts) > 0)
                        <form class="navbar-form navbar-left" role="search" action="{{ url('') }}" method="get">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="{{ trans('messages.searchFor') }}" id="btn-data-search" name="btn-data-search">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                                    </button>
                                </span>
                            </div>
                        </form>
                        <div class="col-md-8 col-md-offset-2">
                            <div class="panel panel-default">
                                <div class="panel-heading text-center"><strong>{{ trans('messages.contactList') }}</strong></div>
                                <div class="panel-body">
                                    <table class="table table-bordered table-hover" id="contactsTable">
                                        <thead>
                                            <th>{{ trans('messages.name') }}</th>
                                            <th>{{ trans('messages.surname') }}</th>
                                            <th>{{ trans('messages.email') }}</th>
                                            <th>{{ trans('messages.phone') }}</th>
                                            <th>{{ trans('messages.actions') }}</th>
                                        </thead>
                                        @foreach ($contacts as $contact)
                                        <tbody>
                                            <tr id="tr_{{ $contact->id }}" data-id="{{ $contact->id }}" class="find">
                                                <td id="name_{{ $contact->id }}">{{ $contact->name}}</td>
                                                <td id="surname_{{ $contact->id }}">{{ $contact->surname}}</td>
                                                <td id="email_{{ $contact->id }}">{{ $contact->email}}</td>
                                                <td id="phone_{{ $contact->id }}">{{ $contact->phone}}</td>
                                                <td>
                                                    <a href="#" class="btn btn-default btn-edit" data-toggle="modal" data-target="#editContactModal" id="btnEdit_{{ $contact->id }}">
                                                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                                    </a>
                                                    <a href="#" class="btn btn-default btn-delete" id="btnDelete_{{ $contact->id }}">
                                                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                                    </a>
                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                    <div class="text-center">
                                        {{-- {{ $contacts->render() }} --}}
                                    </div>
                                </div>
                            </div>
                        </div>
                    @else
                        {{ trans('messages.noContacts') }}
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@include('partials.createContactModal')
@include('partials.editContactModal')
@include('partials.confirmModal')

@endsection

@section('scripts')
    <script src="{{ asset('js/home.js') }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.quicksearch/2.3.0/jquery.quicksearch.min.js"></script>
@endsection

resources/views/index.blade.php
@extends('templates.public')

@section('content')

    <div class="container">
        <div class="content">
            <div class="title">
                <h2><strong>{{ trans('messages.contactBook') }}</strong></h2>
            </div>
            <div class="content">
                <p>{{ trans('messages.contactBookDescription') }}</p>
                <ul>
                    <li>{{ trans('messages.name') }}</li>
                    <li>{{ trans('messages.surname') }}</li>
                    <li>{{ trans('messages.email') }}</li>
                    <li>{{ trans('messages.phone') }}</li>
                    <li>{{ trans('messages.otherDetails') }}</li>
                </ul>
            </div>
        </div>
    </div>

@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Laravel</title>

    <!-- Fonts -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css" integrity="sha384-XdYbMnZ/QjLh6iI4ogqCTaIjrFk87ip+ekIjefZch0Y+PvJ8CDYtEs1ipDmPorQ+" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700">

    <!-- Styles -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    {{-- <link href="{{ elixir('css/app.css') }}" rel="stylesheet"> --}}

    <style>
        body {
            font-family: 'Lato';
        }

        .fa-btn {
            margin-right: 6px;
        }
    </style>
</head>
<body id="app-layout">
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    Laravel
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    <li><a href="{{ url('/home') }}">Home</a></li>
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ url('/login') }}">Login</a></li>
                        <li><a href="{{ url('/register') }}">Register</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{{ url('/logout') }}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>

    @yield('content')

    <!-- JavaScripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.min.js" integrity="sha384-I6F5OKECLVtK/BL+8iSLDEHowSAfUo76ZL9+kGAgTRdiByINKJaqTPH/QVNS1VDb" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    {{-- <script src="{{ elixir('js/app.js') }}"></script> --}}
</body>
</html>

resources/views/partials/confirmModal.blade.php
<div class="modal fade" id="confirmModal" tabindex="-1" role="dialog" aria-labelledby="contactModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="contactModalLabel"><strong>{{ trans('messages.confirmTitle') }}</strong></h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" role="form" method="POST" action="#">
                    {{ csrf_field() }}
                    <div class="input-group">
                        {{ trans('messages.confirmMessageDelete') }}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">{{ trans('messages.no') }}</button>
                        <button type="button" class="btn btn-primary" data-dismiss="modal" id="btnDelete">{{ trans('messages.yes') }}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/partials/createContactModal.blade.php
<div class="modal fade" id="createContactModal" tabindex="-1" role="dialog" aria-labelledby="createContactModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="createContactModalLabel"><strong>{{ trans('messages.newContact') }}</strong></h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" role="form" method="POST" action="{{ route('dashboard.contact.store') }}">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label for="name" class="control-label col-sm-2">{{ trans('messages.name') }}</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="modal_create_name">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="surname" class="control-label col-sm-2">{{ trans('messages.surname') }}</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="modal_create_surname">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="email" class="control-label col-sm-2">{{ trans('messages.email') }}</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="modal_create_email">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="phone" class="control-label col-sm-2">{{ trans('messages.phone') }}</label>
                            <div class="col-sm-10">
                        <input type="text" class="form-control" id="modal_create_phone">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">{{ trans('messages.close') }}</button>
                        <button type="button" class="btn btn-primary" data-dismiss="modal" id="btnSave">{{ trans('messages.save') }}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/partials/editContactModal.blade.php
<div class="modal fade" id="editContactModal" tabindex="-1" role="dialog" aria-labelledby="editContactModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="editContactModalLabel"><strong>{{ trans('messages.editContact') }}</strong></h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" role="form" method="PUT" action="{{ route('dashboard.contact.store') }}">
                    {{ csrf_field() }}
                    <input type="hidden" id="modal_edit_id">
                    <div class="input-group">
                        <a href="#" class="btn btn-default">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>{{ trans('messages.addField') }}
                        </a>
                    </div>
                    </a>
                    <div class="form-group">
                        <label for="name" class="control-label col-sm-2">{{ trans('messages.name') }}</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="modal_edit_name">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="surname" class="control-label col-sm-2">{{ trans('messages.surname') }}</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="modal_edit_surname">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="email" class="control-label col-sm-2">{{ trans('messages.email') }}</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="modal_edit_email">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="phone" class="control-label col-sm-2">{{ trans('messages.phone') }}</label>
                            <div class="col-sm-10">
                        <input type="text" class="form-control" id="modal_edit_phone">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">{{ trans('messages.close') }}</button>
                        <button type="button" class="btn btn-primary" data-dismiss="modal" id="btnUpdate">{{ trans('messages.update') }}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/partials/footer.blade.php
<footer id="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4">
                <h3>{{ trans('messages.nameCompany') }}</h3>
                <p>
                    {{ trans('messages.test') }}
                </p>
            </div>
            <div class="col-md-4">
                <h3>{{ trans('messages.developmentBy') }}</h3>
                <div class="class-info">
                    <p><a href="https://twitter.com/ewcastroh">{{ trans('messages.developer') }}</a></p>
                </div>
            </div>
            <div class="col-md-4">
                <h3>{{ trans('messages.contactMe') }}</h3>
                <i class="fa fa-envelope"><a href="#">{{ trans('messages.developerEmail') }}</a></i>
            </div>
        </div>
    </div>
</footer>

resources/views/partials/header.blade.php
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand main-title" href="{{ url('/') }}">{{ trans('messages.nameCompany') }}</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="{{ url('/') }}">{{trans('messages.home')}}<span class="sr-only">(current)</span></a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                @if (Auth::guest())
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user"></i> <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ url('/login') }}">{{ trans('messages.login') }}</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{{ url('/register') }}">{{ trans('messages.registration') }}</a></li>
                        </ul>
                    </li>
                @else
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            {{ Auth::user()->name . " " . Auth::user()->surname }} <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{{ url('/logout') }}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                        </ul>
                    </li>
                @endif
            </ul>
        </div>
    </div>
</nav>

resources/views/templates/public.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}" />

        <title>@yield('title', trans('messages.nameCompany'))</title>

        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-social/5.0.0/bootstrap-social.css">
        <link rel="stylesheet" href="{{ asset('css/main.css') }}">
    </head>
    <body>
        @include('partials.header')
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-med-offset-2">
                    @yield('content')
                </div>
            </div>
        </div>
        @include('partials.footer')
        <script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s=" crossorigin="anonymous"></script>
        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        @yield('scripts')
    </body>
</html>